"""PDF rendering for case reports.

Every write goes through the `para` / `field` / `heading` helpers, which reset
the cursor to the left margin first. fpdf2 leaves the cursor at the right margin
after a full-width multi_cell, so a raw call sequence silently runs out of
horizontal space partway down the page and raises. Centralising that here means
a new section cannot reintroduce the bug.
"""

from __future__ import annotations

from typing import Any

from app.config import settings

DISCLAIMER = (
    "This report was compiled by TRINETRA, an investigative decision-support "
    "system, from the records held in the platform at the time of generation. "
    "Relationships marked INFERRED are analytical suggestions, not established "
    "facts, and carry no evidentiary weight unless independently corroborated. "
    "TRINETRA does not determine guilt and does not replace authorised human "
    "judgement. All findings require verification by an authorised investigator."
)


def render_pdf(report_ref: str, data: dict[str, Any]) -> bytes:
    from fpdf import FPDF

    def safe(text: Any) -> str:
        # The core PDF fonts are Latin-1; substitute anything outside it rather
        # than failing the whole export.
        return (
            str(text if text is not None else "")
            .encode("latin-1", "replace")
            .decode("latin-1")
        )

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    def para(text: Any, size: float = 9, style: str = "", grey: bool = False,
             height: float = 5) -> None:
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", style, size)
        if grey:
            pdf.set_text_color(96, 96, 96)
        pdf.multi_cell(0, height, safe(text), new_x="LMARGIN", new_y="NEXT")
        if grey:
            pdf.set_text_color(0, 0, 0)

    def heading(text: str) -> None:
        pdf.ln(2.5)
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_fill_color(237, 240, 248)
        pdf.cell(0, 7, safe(text), new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.ln(1)

    def field(label: str, value: Any) -> None:
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 6, safe(label))
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, safe(value), new_x="LMARGIN", new_y="NEXT")

    case = data.get("case", {})
    meta = data.get("meta", {})

    # ------------------------------------------------------------ header
    pdf.set_font("Helvetica", "B", 17)
    pdf.cell(0, 9, safe(f"{settings.APP_NAME} - Investigation Report"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 5, safe(settings.APP_SUBTITLE), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 5,
        safe(f"Report {report_ref}   |   Generated "
             f"{(meta.get('report_generated_at') or '')[:19]}"),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    if meta.get("classification_notice"):
        pdf.set_fill_color(255, 244, 214)
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 9)
        pdf.multi_cell(0, 5, safe(meta["classification_notice"]), fill=True,
                       new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    # -------------------------------------------------------------- case
    heading("Case Details")
    field("Case Number", case.get("case_number"))
    field("Title", case.get("title"))
    field("Status", case.get("status"))
    field("Priority", case.get("priority"))
    field("Module", case.get("module"))
    field("Owner", case.get("owner"))
    field("Opened", (case.get("opened_at") or "")[:10])
    generator = meta.get("generated_by", {})
    field("Generated by",
          f"{generator.get('name', '')} ({generator.get('service_id', '')})")
    if case.get("description"):
        field("Description", case["description"])

    team = data.get("team", [])
    if team:
        heading(f"Case Team ({len(team)})")
        for member in team:
            para(f"- {member.get('name')} ({member.get('service_id')}) - "
                 f"{member.get('role_on_case')}, {member.get('designation')}")

    # ----------------------------------------------------------- summary
    heading("Summary")
    for key, value in (data.get("summary") or {}).items():
        field(key.replace("_", " ").title(), value)

    # ---------------------------------------------------------- entities
    entities = data.get("entities", [])
    if entities:
        heading(f"Entities ({len(entities)})")
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(58, 6, "Name")
        pdf.cell(30, 6, "Type")
        pdf.cell(30, 6, "Role")
        pdf.cell(22, 6, "Priority")
        pdf.cell(0, 6, "Band", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for entity in entities[:60]:
            pdf.set_x(pdf.l_margin)
            pdf.cell(58, 5.5, safe(entity.get("name", ""))[:33])
            pdf.cell(30, 5.5, safe(entity.get("type", "")))
            pdf.cell(30, 5.5, safe(entity.get("role_in_case") or "-")[:17])
            score = entity.get("priority_score")
            pdf.cell(22, 5.5, safe(score if score is not None else "-"))
            pdf.cell(0, 5.5, safe(entity.get("priority_band") or "-"),
                     new_x="LMARGIN", new_y="NEXT")

    # ----------------------------------------------------- relationships
    relationships = data.get("relationships", {})
    for key, label in (
        ("observed", "Observed Relationships"),
        ("validated", "Investigator-Validated Relationships"),
        ("inferred_pending_validation", "Inferred - Pending Validation"),
        ("rejected", "Rejected by Investigator"),
    ):
        rows = relationships.get(key, [])
        if not rows:
            continue
        heading(f"{label} ({len(rows)})")
        if key == "inferred_pending_validation":
            para(
                "The following are analytical suggestions awaiting investigator "
                "validation. They are not established facts and carry no "
                "evidentiary weight.",
                style="I", grey=True,
            )
        for row in rows[:40]:
            para(
                f"- {row.get('source')} -[{row.get('type')}]-> {row.get('target')}"
                f"   confidence {row.get('confidence')}"
                f"   source: {row.get('source_ref') or 'n/a'}"
            )
            if row.get("reason"):
                para(f"      Reason: {row['reason']}",
                     size=8, style="I", grey=True, height=4.4)

    # --------------------------------------------------- network findings
    findings = data.get("network_findings") or {}
    if findings.get("most_connected"):
        heading("Network Findings")
        for row in findings["most_connected"]:
            para(f"- {row.get('name')} ({row.get('type')}): "
                 f"{row.get('connections')} connections")
        if findings.get("method"):
            para(findings["method"], size=8, style="I", grey=True, height=4.4)

    # ---------------------------------------------------------- timeline
    timeline = data.get("timeline", [])
    if timeline:
        heading(f"Timeline ({len(timeline)} events)")
        for event in timeline[:60]:
            when = event.get("time_label") or (event.get("occurred_at") or "")[:16]
            para(f"- {when}  [{event.get('type')}]  {event.get('title')}")

    # ---------------------------------------------------------- priority
    priority_rows = data.get("priority_analysis", [])
    if priority_rows:
        heading("Investigation Priority Analysis")
        para(
            "Investigation Priority Score is an analytical triage signal derived "
            "from recorded data. It is not a measure of guilt, criminality or "
            "involvement in any offence.",
            style="I", grey=True,
        )
        for row in priority_rows:
            para(f"- {row.get('entity')}: {row.get('score')} ({row.get('band')}), "
                 f"confidence {row.get('confidence')}")
            for factor in row.get("top_factors", []):
                para(f"      {factor.get('label')}: {factor.get('detail')}",
                     size=8, grey=True, height=4.4)

    # ---------------------------------------------------------- evidence
    evidence = data.get("evidence", [])
    if evidence:
        heading(f"Evidence ({len(evidence)})")
        for item in evidence[:40]:
            para(f"- {item.get('evidence_ref')}  [{item.get('source_type')}]  "
                 f"{item.get('description')}")
            para(f"      Source: {item.get('source')}   "
                 f"Status: {item.get('status')}   "
                 f"Confidence: {item.get('confidence')}",
                 size=8, grey=True, height=4.4)

    # ----------------------------------------------------- women safety
    women_safety = data.get("women_safety")
    if women_safety:
        heading("Women Safety")
        for incident in women_safety.get("incidents", [])[:30]:
            para(f"- [{incident.get('priority')}] {incident.get('incident_ref')} "
                 f"{incident.get('type')} at "
                 f"{incident.get('location') or 'unspecified'} "
                 f"({incident.get('time_label') or (incident.get('occurred_at') or '')[:10]})")
        for sos in women_safety.get("sos", []):
            transitions = " -> ".join(t.get("to", "") for t in sos.get("transitions", []))
            para(f"- SOS {sos.get('alert_ref')} [{sos.get('status')}] subject "
                 f"{sos.get('subject')}; location source "
                 f"{sos.get('location_source')}; workflow: {transitions}")
        for pattern in women_safety.get("patterns", []):
            para(f"- Pattern {pattern.get('pattern_ref')}: {pattern.get('title')} "
                 f"(confidence {pattern.get('confidence')}, {pattern.get('status')})")

    # ------------------------------------------------ decisions and notes
    validations = data.get("investigator_validation", [])
    if validations:
        heading(f"Investigator Decisions ({len(validations)})")
        for decision in validations[:40]:
            para(
                f"- {decision.get('decision')} by {decision.get('by')} on "
                f"{(decision.get('timestamp') or '')[:19]}"
                + (f" - {decision.get('rationale')}" if decision.get("rationale") else "")
            )

    notes = data.get("notes", [])
    if notes:
        heading(f"Case Notes ({len(notes)})")
        for note in notes[:25]:
            para(f"- {note.get('author')} "
                 f"({(note.get('created_at') or '')[:16]}): {note.get('body')}")

    # -------------------------------------------------------- disclaimer
    pdf.ln(4)
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "Disclaimer", new_x="LMARGIN", new_y="NEXT")
    para(data.get("disclaimer", DISCLAIMER), size=8, style="I", grey=True, height=4.5)

    return bytes(pdf.output())
