/** Case report generation, preview and export. */

import {
  html, useState, useCallback,
  Card, Button, Pill, EvidenceBadge, EmptyState, LoadingBlock, ErrorBlock,
  Disclaimer, useAsync, fmt, BAND_COLORS, useToast,
} from "../lib/ui.js";
import { api, download } from "../api/client.js";

export function ReportsPage({ navigate, user, caseId, params }) {
  const [selectedCase, setSelectedCase] = useState(
    caseId || (params.case_id ? Number(params.case_id) : null)
  );
  const [preview, setPreview] = useState(null);
  const [loadingPreview, setLoadingPreview] = useState(false);
  const [generating, setGenerating] = useState(false);
  const toast = useToast();
  const canExport = (user.permissions || []).includes("data:export");

  const cases = useAsync(() => api.get("/cases"), []);
  const reports = useAsync(
    () => api.get("/reports", selectedCase ? { case_id: selectedCase } : {}),
    [selectedCase]
  );

  const loadPreview = useCallback(async (id) => {
    setLoadingPreview(true);
    try {
      setPreview(await api.get(`/reports/case/${id}/preview`));
    } catch (err) {
      toast.push(err.message, "error");
    } finally {
      setLoadingPreview(false);
    }
  }, [toast]);

  const generate = useCallback(async () => {
    if (!selectedCase) return;
    setGenerating(true);
    try {
      const created = await api.post(`/reports/case/${selectedCase}/generate`);
      toast.push(`Report ${created.report_ref} generated from stored case data.`, "success");
      reports.reload();
    } catch (err) {
      toast.push(err.message, "error");
    } finally {
      setGenerating(false);
    }
  }, [selectedCase, reports, toast]);

  const exportFile = useCallback(async (reportRef, format) => {
    try {
      await download(`/reports/${reportRef}/${format}`, `${reportRef}.${format}`);
      toast.push(`${format.toUpperCase()} downloaded.`, "success");
    } catch (err) {
      toast.push(err.message, "error");
    }
  }, [toast]);

  return html`<div>
    <div className="page-head">
      <div className="page-head-main">
        <h1>Case Reports</h1>
        <p>
          Reports are compiled from the records held at the moment of generation and
          stored as a snapshot, so a report stays a faithful record of what the case
          looked like when it was produced.
        </p>
      </div>
    </div>

    <${Card} className="mb-2">
      <div className="row">
        <span className="small strong">Case</span>
        ${(cases.data?.items || []).map((item) => html`<button
          key=${item.id} className=${`chip ${selectedCase === item.id ? "active" : ""}`}
          onClick=${() => { setSelectedCase(item.id); setPreview(null); }}
        >${item.case_number}</button>`)}
        <div className="spacer"></div>
        ${selectedCase
          ? html`
              <${Button} key="prev" size="sm" onClick=${() => loadPreview(selectedCase)} loading=${loadingPreview}>
                Preview
              <//>
              <${Button} key="gen" size="sm" variant="primary" onClick=${generate} loading=${generating}>
                Generate report
              <//>`
          : null}
      </div>
    <//>

    ${!selectedCase
      ? html`<${EmptyState} icon="▧" title="Select a case" text="Choose a case above to preview or generate a report." />`
      : null}

    ${loadingPreview ? html`<${Card}><${LoadingBlock} rows=${6} /><//>` : null}

    ${preview ? html`<${ReportPreview} data=${preview} navigate=${navigate} />` : null}

    <${Card} title="Generated reports" className="mt-2">
      ${reports.loading ? html`<${LoadingBlock} rows=${3} />` : null}
      ${reports.data?.items?.length
        ? html`<div className="table-wrap">
            <table className="data">
              <thead><tr>
                <th>Reference</th><th>Case</th><th>Generated by</th><th>When</th>
                <th className="num">Entities</th><th className="num">Relationships</th><th>Export</th>
              </tr></thead>
              <tbody>
                ${reports.data.items.map((report) => html`<tr key=${report.report_ref}>
                  <td className="mono">${report.report_ref}</td>
                  <td>${report.case_number}</td>
                  <td className="tiny">${report.generated_by}</td>
                  <td className="tiny nowrap">${fmt.dateTime(report.generated_at)}</td>
                  <td className="num">${fmt.number(report.summary?.entities || 0)}</td>
                  <td className="num">${fmt.number(report.summary?.relationships || 0)}</td>
                  <td>
                    ${canExport
                      ? html`<div className="row" style=${{ gap: "5px" }}>
                          <${Button} size="sm" onClick=${() => exportFile(report.report_ref, "pdf")}>PDF<//>
                          <${Button} size="sm" onClick=${() => exportFile(report.report_ref, "json")}>JSON<//>
                        </div>`
                      : html`<span className="tiny muted">Export not permitted</span>`}
                  </td>
                </tr>`)}
              </tbody>
            </table>
          </div>`
        : html`<${EmptyState} title="No reports yet" text="Generate a report to see it listed here." />`}
    <//>
  </div>`;
}

function ReportPreview({ data, navigate }) {
  const summary = data.summary || {};
  const relationships = data.relationships || {};

  return html`<${Card}
    title=${`Report preview — ${data.case.case_number}`}
    subtitle=${`${data.case.title} · generated ${fmt.dateTime(data.meta.report_generated_at)}`}
  >
    ${data.meta.classification_notice
      ? html`<div className="alert alert-warn"><span>⚠</span><div>${data.meta.classification_notice}</div></div>`
      : null}

    <div className="grid-4 mb-2">
      ${Object.entries(summary).map(([key, value]) => html`<div key=${key}>
        <div className="kpi-label">${fmt.title(key)}</div>
        <div style=${{ fontSize: "18px", fontWeight: 700 }}>${fmt.number(value)}</div>
      </div>`)}
    </div>

    <div className="card-title mb-1">Key entities</div>
    <div className="table-wrap mb-2">
      <table className="data">
        <thead><tr><th>Name</th><th>Type</th><th>Role</th><th>Priority</th></tr></thead>
        <tbody>
          ${(data.entities || []).slice(0, 15).map((entity) => html`<tr key=${entity.uid} className="clickable"
            onClick=${() => navigate(`/entity/${entity.uid}`)}>
            <td className="strong">${entity.name}</td>
            <td>${fmt.title(entity.type)}</td>
            <td>${entity.role_in_case || "—"}</td>
            <td>${entity.priority_band
              ? html`<${Pill} kind=${entity.priority_band}>${fmt.score(entity.priority_score)}<//>`
              : "—"}</td>
          </tr>`)}
        </tbody>
      </table>
    </div>

    ${[
      ["observed", "Observed relationships", "green"],
      ["validated", "Investigator-validated", "green"],
      ["inferred_pending_validation", "Inferred — pending validation", "inferred"],
      ["rejected", "Rejected by investigator", "rejected"],
    ].map(([key, label]) => {
      const rows = relationships[key] || [];
      if (!rows.length) return null;
      return html`<div key=${key} className="mb-2">
        <div className="card-title mb-1">${label} <span className="card-sub">(${rows.length})</span></div>
        ${key === "inferred_pending_validation"
          ? html`<div className="tiny muted mb-1">
              These are analytical suggestions awaiting validation. They are not established facts.
            </div>`
          : null}
        ${rows.slice(0, 8).map((row) => html`<div className="kv-row" key=${row.id}>
          <span className="kv-key">${row.source} → ${row.type} → ${row.target}</span>
          <span className="kv-val">
            <${EvidenceBadge} status=${row.evidence_status} />
            <span className="tiny muted"> ${fmt.percent(row.confidence)}</span>
          </span>
        </div>`)}
        ${rows.length > 8 ? html`<div className="tiny muted mt-1">…and ${rows.length - 8} more in the full report.</div>` : null}
      </div>`;
    })}

    ${data.priority_analysis?.length
      ? html`<div className="mb-2">
          <div className="card-title mb-1">Investigation priority analysis</div>
          ${data.priority_analysis.slice(0, 6).map((row, i) => html`<div className="kv-row" key=${i}>
            <span className="kv-key">${row.entity}</span>
            <span className="kv-val" style=${{ color: BAND_COLORS[row.band] }}>
              ${fmt.score(row.score)} ${row.band}
            </span>
          </div>`)}
        </div>`
      : null}

    ${data.women_safety
      ? html`<div className="mb-2">
          <div className="card-title mb-1">Women Safety</div>
          <div className="small muted mb-1">
            ${data.women_safety.incidents?.length || 0} incidents ·
            ${data.women_safety.alerts?.length || 0} alerts ·
            ${data.women_safety.sos?.length || 0} SOS ·
            ${data.women_safety.patterns?.length || 0} patterns
          </div>
          ${(data.women_safety.patterns || []).map((pattern) => html`<div className="kv-row" key=${pattern.pattern_ref}>
            <span className="kv-key">${pattern.title}</span>
            <span className="kv-val">${fmt.percent(pattern.confidence)}</span>
          </div>`)}
        </div>`
      : null}

    ${data.investigator_validation?.length
      ? html`<div className="mb-2">
          <div className="card-title mb-1">Investigator decisions (${data.investigator_validation.length})</div>
          ${data.investigator_validation.slice(0, 8).map((decision, i) => html`<div className="kv-row" key=${i}>
            <span className="kv-key">${fmt.dateTime(decision.timestamp)} — ${decision.by}</span>
            <span className="kv-val"><${EvidenceBadge} status=${decision.decision} /></span>
          </div>`)}
        </div>`
      : null}

    <${Disclaimer}>${data.disclaimer}<//>
  <//>`;
}
